# Generated by Django 5.0 on 2024-06-17 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Not Known', max_length=20)),
                ('sub_category', models.CharField(blank=True, max_length=20)),
                ('prod_name', models.CharField(default='default ', max_length=20)),
                ('Description', models.CharField(default='default ', max_length=1000)),
                ('price', models.IntegerField(default=0)),
                ('img', models.ImageField(default='Not available', upload_to='media')),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Not Known', max_length=20)),
                ('sub_category', models.CharField(blank=True, max_length=20)),
                ('prod_name', models.CharField(default='default', max_length=20)),
                ('Description', models.CharField(default='default', max_length=1000)),
                ('price', models.IntegerField(default=0)),
                ('img', models.ImageField(default='Not available', upload_to='media')),
                ('discount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50)),
                ('email', models.CharField(default='default', max_length=70)),
                ('phone', models.CharField(default='default', max_length=11)),
                ('description', models.TextField(default='default', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default ', max_length=20)),
                ('caddress', models.CharField(default='default ', max_length=20)),
                ('maddress', models.CharField(default='default ', max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('email', models.EmailField(default='default', max_length=254)),
                ('phone', models.CharField(default='default ', max_length=12)),
                ('product_name', models.CharField(default='default ', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
